### ISSUE TITLE
Name of vendor in listing too small

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools#23]
Name of tool :  XYZ by xyzI 
I feel the "by xyz" is too small

**Comment by hidde** [comment]
Thanks for the feedback, I've slightly updated the issue title.

**Comment by hidde** [comment]
I'll add the rationale behind this design: for me, the name of the tool is primary, the name of the vendor is secondary. This contrast is implemented visually by using a smaller size and decrease in font weight ('regular' instead of 'bold').

I feel when I make the text same size, there is not enough contrast, so that it becomes harder to scan.

Screenshot for reference: 

<img width="701" alt="tools listed like in real tool, but with vendor name text size increased to be the same as tool name" src="https://user-images.githubusercontent.com/178782/67086776-cf369400-f1a1-11e9-87d9-baa8778ee7b7.png">

**Comment by hidde** [comment]
Suggested solution: keep as is, with vendor slightly smaller than name of tool.

**Comment by hidde** [comment]
@vmmiller could you please indicate if you are okay with keeping it as is? Please respond on or before Monday 18 November.

**Comment by slhenry** [comment]
I agree with making the tool name more prominent than the vendor name.

For me, the screen shot above works great. Because tool is first and bold, I focus on the tool name. I can easily ignore the vendor name. (I also note the latest draft has them underlined, so they stand out even more.)

Every instance of different font size, weight, style, etc. adds visual complexity.

![image](https://user-images.githubusercontent.com/6991814/68786757-f304c280-0605-11ea-91cd-79c3d4db45fa.png)

For me the change in font size:
* adds visual complexity and makes it look cluttered
* actually **draws my attention to the vendor name** because my brain says: _"this is different, look at it!"_ (and also, I have to strain to read the smaller text, so it slows down my processing the info.)

[medium] I support same text size.

**Comment by hidde** [comment]
I've addressed this and made the vendor name the same size as the tool name.

**Comment by vmmiller** [comment]
Sorry for the delay in replying.  Yes, it's fine.

**Comment by hidde** [comment]
Thank you Vicki!
