### ISSUE TITLE
Remove "See full list of accessibility features" from every Details section

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-authoring-tools#31]
I don't think we want this link in each tool detail listing. Instead, make it very clearly linked elsewhere -- probably in the intro and probably also above &/or below that filter section.

**Comment by yatil** [comment]
I like to have it in context.

**Comment by yatil** [comment]
Expanding on it: Many users will just use the tool and not think about finding extra referenced information somewhere else, but as the shorthands are not easy to understand for almost every user, having a legend handy right there is nice. (I could even see a slide-over panel from the right, so you could cross reference the legend. But that would be scope creep :-D)

**Comment by iadawn** [comment]
Was thinking about this, and for my small brain and memory, and because some of the accessibility feature short descriptions are unclear, I might even suggest linking every feature to it's description somehow!! Ok, that is waaay too much, however, there is an issue here I think.

This might be because some of the features are unclear and that might address the problem. However, at the moment I am finding myself looking at the features in the tool list and wondering what some of them mean. Then I hunt for the link to the full list of features in order to find it.

Perhaps a link to each section of success criteria (for content editors, for end users) could be included beside the legend for the filters? This would at least connect the link more contextually with the features.

**Comment by hidde** [comment]
We discussed this in EOWG on Friday, suggestions from that discussion:

* Turn each feature into a Show/Hide that expands a definition (Hidde to propose visual design for this)

If anyone has other suggestions, feel free to add them here.

**Comment by yatil** [comment]
I don’t feel like having a show/hide with every item is a good idea. First, it will blow up the page size. Second, it will make it even harder to scan. Also this resolution seems to be the exact opposite of what this issue was initially opened for (remove duplication).

**Comment by iadawn** [comment]
I agree with @yatil in that this would probably be way to much. I think just having a link in the header is way too little. I wonder if there is an option to include a link to the relevant section (Accessibility for content editors or Accessibility for end users) in the left hand filter panel.

There aren't actually that many Success Criteria and the Features List page is a good short summary so I don't know that it would need to link to every individual SC. This might help make the link much more apparent than the phrasing and positioning of 'Feature List'

**Comment by hidde** [comment]
I like the suggestion of including it in the filters rather than in the Details section. 

Wording would matter a lot, I think… how can we best phrase it so that it is immediately clear that it goes to a list of features and their descriptions? Brainstorming:

<img width="261" alt="content editor features explained" src="https://user-images.githubusercontent.com/178782/67939348-a5359680-fbd1-11e9-8566-ebc36d45a779.png"> <img width="245" alt="view documentation" src="https://user-images.githubusercontent.com/178782/67939356-a961b400-fbd1-11e9-8d3b-6fd470eca124.png">  

Or perhaps it could be an icon with one of the above as the underlying link text?

<img width="253" alt="question mark icon" src="https://user-images.githubusercontent.com/178782/67939768-8a175680-fbd2-11e9-9463-94832ab0fd23.png">

**Comment by iadawn** [comment]
Icon would get my vote, only because it is nicely succinct

**Comment by hidde** [comment]
And we could make it appear alongside other feature listings, i.e. the one that is in the Details panel.

<img width="665" alt="" src="https://user-images.githubusercontent.com/178782/67940200-82a47d00-fbd3-11e9-8fd9-58cb9d9f5abe.png">

**Comment by yatil** [comment]
Icon would work for me.

**Comment by hidde** [comment]
I have added this with the icon. Note the icon is slightly different from screenshot above, the new one is from FontAwesome (where most of our other icons are from).

![](https://user-images.githubusercontent.com/178782/68868315-9eda0b00-06f7-11ea-8a6d-10d9e811215e.png)

**Comment by bakkenb** [comment]
I like the icon idea too. Clean and expected outcome of "further detail to help you understand." 

@yatil, Do we have some sort of design standard for this type of icon usage on the WAI site? Seems like it should be consistent with current use if we already have this implemented in other resource(s).

**Comment by bakkenb** [comment]
I would suggest we use the same design if we still like it.

**Comment by yatil** [comment]
Those are the same icons IIRC. @bakkenb We just use FontAwesome where we can, as Hidde said.

**Comment by yatil** [comment]
BTW: Commenting on closed issues means some people are not really notified. If it is an issue please reopen the issue or create a new issue if it is something different.
